### ISSUE TITLE
External crates

### ISSUE THREAD

**Issue by mcanders** [edubkendo/atom-racer#26] opened 2015-06-02 04:38 UTC
atom-racer is working great for completions from std and the current file in a project but it does not show completions from external crates and other files in the current project.  I was under the impression that racer supported external crates, reading dependencies from Cargo.toml files, and detecting the .cargo folder. Should these features work in atom-racer?  Am I doing something wrong?

**Comment by alkama** [comment] 2015-06-05 14:50
Hello,

AFAIK, we provide "racer":
- as `RUST_SRC_PATH`: 
  * the user configured **rustc sources** along with
  * the **current Atom project paths**
- as input for completion:
  * the **currently edited buffer** (and current editing position).

Racer does the rest and I dont know if it does special things to handle cargo.

**Comment by edubkendo** [comment] 2015-06-05 15:23
Maybe @phildawes could shed some light?

**Comment by phildawes** [comment] 2015-06-06 10:20
Hello! Yes, racer should work with cargo. Also you say it doesn't work for files in the current project? Can you give an example please?
Thanks!

**Comment by alkama** [comment] 2015-06-07 22:24
I think I know where the problem is:
We pass the current buffer to complete as a temporary file that is created in the systems temporary directory. And from what I understood, Racer is using that file's base path to search for a `Cargo.toml`.

We should probably switch to a strategy of writing the temp file at the root of the current project path so that it's found.
(Although I'm scared it might do strange flickers in sidebar due to adding and deleting files constantly while typing. Or find a way to force Atom to ignore our temporary file extensions).

I also have to check if Racer actually uses multiple values in `RUST_SRC_PATH` since we pass the current project path along with the rustc source using that environment variable.

**Comment by mcanders** [comment] 2015-06-07 22:39
That definitely seems like the problem.  Racer does use the open file and the multiple values in RUST_SRC_PATH because when I changed the project_path part of the RUST_SRC_PATH generated by atom-racer to project_path/src, it resulted in completing the names of the modules in project_path.  Oddly, it did not provide completions for anything in the modules, just their names.

**Comment by mcanders** [comment] 2015-06-07 22:48
Come to think of it, maybe it is only completing the names because it only loads "project_path/src/lib.rs" and not the source files in folders such as "project_path/src/MODULE_NAME".

Additionally, are the temporary files properly deleted after every racer invocation?  If so, moving the temporary files to the project's root could result in some serious clutter in a folder that should really remain clean.

**Comment by edubkendo** [comment] 2015-06-08 22:51
Should be fixed by #29

**Closed by edubkendo** 2015-06-08 22:51 UTC
Labels: enhancement
